### ISSUE TITLE
11t needs emojis

### ISSUE THREAD

**Issue by ghost** [jeroensmeets/mastodon-app#102]
I think the easy way is to usw the andoid system one.

https://developer.android.com/topic/libraries/support-library/preview/emoji-compat.html

**Comment by ghost** [comment]
Or we use this

https://www.emojione.com/

**Comment by jeroensmeets** [comment]
@beli3ver as 11t is written in FuseTools, it needs other libraries. Will keep your entry as enhancement, thanks.

**Comment by ghost** [comment]
https://www.fusetools.com/docs/fuse/controls/text

Then this

Am 23. Juli 2017 10:34:30 MESZ schrieb Jeroen Smeets <notifications@github.com>:
>@beli3ver as 11t is written in FuseTools, it needs other libraries.
>Will keep your entry as enhancement, thanks.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jeroensmeets/mastodon-app/issues/102#issuecomment-317237818

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jeroensmeets** [comment]
Hi I'm closing all old issues from 2017 as I'm starting this app up again in a new development environment.
