### ISSUE TITLE
Last version missing in releases/ ?

### ISSUE THREAD

**Issue by IzzySoft** [jeroensmeets/mastodon-app#104]
Playstore reports version 1.5, but https://github.com/jeroensmeets/releases ends at v1.3.28. Could you please add the latest release here as well? Otherwise, this project's Readme is wrong, stating it would be available in my repo :wink:

**Comment by IzzySoft** [comment]
@jeroensmeets any chance for the new tags? There's even an [RFP at F-Droid](https://gitlab.com/fdroid/rfp/issues/167) waiting for them meanwhile. So could you please at least give a statement? Without you maintaining the tags, that F-Droid build is rather unlikely.

**Comment by jeroensmeets** [comment]
Hi Izzy, thanks for your concern. The current version is just not good enough, and I have already removed it from the iOS App Store. Android is a bit better, but I'm missing some essential components in FuseTools to improve 11t. As long as these are not available, there's not much use in working on it.

**Comment by IzzySoft** [comment]
@jeroensmeets thanks a lot for your response! As in above mentioned [RFP](https://gitlab.com/fdroid/rfp/issues/167) at F-Droid folks already consider your app dead ("Latest commit on Mar 26, 2018") – can I take this as statement you're still developing it (and just had a break)? Or did you mean that as those components are missing, you gave up on it?

**Comment by IzzySoft** [comment]
Great to see the repo becoming active again, yay! :crossed_fingers: for a new release then. Any ETA already?

**Comment by jeroensmeets** [comment]
@IzzySoft hi! Yes, active, but no release in my planning, so no ETA as well. I hope to make this into an app that supports Pixelfed, as I would like to have that app myself :-) Thanks for your comment!

**Comment by IzzySoft** [comment]
It's ready when it's ready, no pressure :smile: And all :crossed_fingers: for good progress! Just happy the elevent wasn't killed for its teeth :rofl:

**Comment by IzzySoft** [comment]
So you're still keeping it alive? That RFP on F-Droid now sits unprocessed for 3 years. Afraid we'll have to close it for now. Please give me a ping should you woke it again and released it, so we can revive its partner on our end.

**Comment by jeroensmeets** [comment]
@IzzySoft fair. I'll let you know.

**Comment by IzzySoft** [comment]
Just wondering, @jeroensmeets: will you bring it back, or is 11t rather EOL? Does the last release from 2017 still work with current Mastodon versions, or should we rather remove it from IzzyOnDroid?

**Comment by jeroensmeets** [comment]
Hi @IzzySoft good intentions aside, the app is EOL. Have been building a new version but that is far from usable. So please remove it if you will.

**Comment by IzzySoft** [comment]
Thanks Jeroen! I know "hope dies last", and it's sometimes hard to admit to be "defeated by time". Guess this is such a case. Should a good fairy pass some fairy dust, give me a ping and we can revive 11t anytime. All the best for you, and thanks for all!
