### ISSUE TITLE
no visual feedback from repost/favourite buttons

### ISSUE THREAD

**Issue by jeroensmeets** [jeroensmeets/mastodon-app#2]
1. the favourite and repost buttons don't show we are waiting for a confirmation from the server
2. the icons do not change when the action have finished successfully

**Comment by mistydemeo** [comment]
Looks like in the current version, there is a loading animation and the icons change, but the count doesn't increment.

**Comment by jeroensmeets** [comment]
fixed in code, will be released in 1.0.14
