### ISSUE TITLE
parsing error for @ references when user is on other instance

### ISSUE THREAD

**Issue by jeroensmeets** [jeroensmeets/mastodon-app#28]
parsing error for @ references cross server when the person being referenced isn't on the same origin as matador user

**Comment by Gargron** [comment]
Here is how the mastodon web UI completes this task:

Along with the status you get `mentions`, an array of objects with `url` attributes. Match all `<a>` tags in the body of the status, and see if there is a mention where `url == href`, if so, replace the `<a>` tag with whatever your code needs to use to handle profile links.

**Comment by jeroensmeets** [comment]
@Gargron I have to replace the `<a href=""` with click events in the app. A post is not in a webview (too slow).

**Comment by jeroensmeets** [comment]
profile on other instance opens in browser now. (since version 1.0.10)
