### ISSUE TITLE
No toots on first start

### ISSUE THREAD

**Issue by jelv** [jeroensmeets/mastodon-app#31]
![img_0125](https://cloud.githubusercontent.com/assets/7106279/20876642/c90d4ff0-bac3-11e6-9b32-89f37396d83a.PNG)

Installed the app and logged in but the toots didnt load. The logo kept spinning but nothing loaded. Switched WiFi of to 4g but still nothing loaded. Closed and reopened and still nothing loaded. After force quiting it loaded the first toots.

**Comment by jeroensmeets** [comment]
Fixed in beta v1.0.7
