### ISSUE TITLE
11t needs translations

### ISSUE THREAD

**Issue by jeroensmeets** [jeroensmeets/mastodon-app#35]

**Comment by jeroensmeets** [comment]
once app is translatable:
nl: @jeroensmeets
de: @DominicDev, @beli3ver
Japanese/Korean: @transifex3
Spanish: @jiserra

**Comment by domiSoap** [comment]
Hi Jeroen,

How do you develop Matodor and which Tools are you using?

This is the first time i want to help in an open-source Project, do you have some tips for starting
honorary programming?

**Comment by jeroensmeets** [comment]
Most info is in the README. Let me know if you need more.

**Comment by domiSoap** [comment]
Hi Hören, there happen some Bugs with the Matodor app, i send you the
Report of Bugs ;)
---------- Weitergeleitete Nachricht ----------
Von: "Dominic Seifert" <dominic.seifert.dev@gmail.com>
Datum: 07.12.2016 6:51 nachm.
Betreff: bugreport-2016-12-07-18-48-17.zip
An: "Domi A" <dominicseifert997@gmail.com>
Cc:

surnia_vfeu-user 6.0 MPI24.65-39 23 release-keys
>

**Comment by domiSoap** [comment]
Can you permit that i can do my commit with my featurebranch, so that you later insert your dutch translation?

**Comment by jeroensmeets** [comment]
Hi @domiSoap -- you can send me your changes by making a pull request.

**Comment by domiSoap** [comment]
Ok, i will do this ;)

**Comment by ghost** [comment]
Here for some Asian languages support, like Japanese and Korean!
How about to use translation platforms like [Crowdin](https://crowdin.com/)?

**Comment by jiserra** [comment]
I'm offering myself to translate the app to Spanish.

**Comment by jeroensmeets** [comment]
@domiSoap @transifex3 @jiserra thanks for the offer. For translating, FuseTools has no ready localization system, so I/we have to add code for translating strings. Once that's in, we can make files to store custom languages.
