### ISSUE TITLE
responsiveness issues

### ISSUE THREAD

**Issue by ghost** [jeroensmeets/mastodon-app#40]
top bar of options, toot, home, notifications and public timeline, do not respond quickly or informatively. almost as if they are lagging.

faving or boosting a toot has a similar problem: no change in icon or anything, i rarely  know if i actually faved the toot

**Comment by jeroensmeets** [comment]
fav/boost give feedback now; the top menu should have some visual feedback when you press it

**Comment by jeroensmeets** [comment]
fixed in 1.0.10
