### ISSUE TITLE
better UI for public timeline, and search/possibly favorite for hashtags

### ISSUE THREAD

**Issue by ghost** [jeroensmeets/mastodon-app#41]
the public timeline option in the UI carries way too far over to the right for my tiny phone, i would heavily suggest making a drop down menu from the icon for mastodon, in which public timeline and any 'favorite'd hashtags would appear, alongside a settings option maybe, someday. IDEALLY i would also appreciate a list of accounts you own so that i could swap between two accounts if i wanted, but that is less of an issue Right Now, and more of a lofty feature request that would reside in the same space

**Comment by jeroensmeets** [comment]
menu has been changed in version 1.0.10 so it fits on smaller screen, the option to show favorites/hashtags is nice but not for now.
