### ISSUE TITLE
GIF display pics not loading

### ISSUE THREAD

**Issue by puphime** [jeroensmeets/mastodon-app#48]
as seen below, certain users have no icon (on Android 6.0.1, Asus ZenFone 2). This issue persists across app restarts.
![media](https://cloud.githubusercontent.com/assets/24903509/21625390/b9d3ec38-d20b-11e6-9582-2e9c8aa83447.png)

**Comment by jeroensmeets** [comment]
Correct, this is for avatars when uploaded as GIF (animated and non-animated).

**Comment by puphime** [comment]
yeah i just noticed and was going to add. fix still would be nice

**Comment by puphime** [comment]
following up, GIF avatars are now displaying, but they are too big -> cropped and display above the menu bar when scrolling

**Comment by jeroensmeets** [comment]
removed again in version 1.0.10, when FuseTools gets support for animated GIFs i'll add them back in.
