### ISSUE TITLE
JavaScript error in assets/js/api line 3. require() module not found assets/js/auth

### ISSUE THREAD

**Issue by forivall** [jeroensmeets/mastodon-app#49]
I tried to build it myself, but it appears that you haven't pushed the auth.js file.
![screen shot 2017-01-04 at 12 03 24 pm](https://cloud.githubusercontent.com/assets/760204/21657135/d0f3bfaa-d275-11e6-917d-17b85ac9c58f.png)

**Comment by jeroensmeets** [comment]
You're correct, and it's on purpose. The CLIENT_ID and CLIENT_SECRET are specific for my build. It is easy to get your own, see the readme file:

https://github.com/jeroensmeets/mastodon-app#build-it-yourself
