### ISSUE TITLE
No placeholder for empty profile 

### ISSUE THREAD

**Issue by mistydemeo** [jeroensmeets/mastodon-app#50]
If a user hasn't selected an avatar, display name and profile text, their profile page simply displays a large empty area without any form of placeholder. Screenshot shows my own user page.

![img_4834](https://cloud.githubusercontent.com/assets/780485/21661231/f8001d5c-d287-11e6-831c-19650367357c.PNG)

**Comment by jeroensmeets** [comment]
this was fixed in one of the v1.3 versions.
