### ISSUE TITLE
Threads incorrectly show toots from another thread

### ISSUE THREAD

**Issue by mistydemeo** [jeroensmeets/mastodon-app#52]
There are two distinct bugs here:

1) When clicking through to the detail view of a toot, Matodor shows the last thread that you clicked through to until the new one has loaded.

2) If the new thread has fewer toots than the lat thread you were viewing, Matodor will still show toots from the old thread for any toots that aren't replaced. Screenshot attached.

![img_4837](https://cloud.githubusercontent.com/assets/780485/21661908/80a125ea-d28b-11e6-81b3-3b1c3a8aa01f.PNG)

**Comment by jeroensmeets** [comment]
fixed in 1.0.10
