### ISSUE TITLE
Show profile pictures that are animated GIFs

### ISSUE THREAD

**Issue by mkosler** [jeroensmeets/mastodon-app#57]
On Android, when I scroll through the public timeline, if a tooter has an animated gif as their profile picture, it kind of "floats" awkwardly as I scroll up and down. They also get drawn in front of the menu bar, while non-animated images get correctly drawn behind the menu bar.

**Comment by mkosler** [comment]
[Example of gif profile pictures drawing above the menu bar](http://i.imgur.com/qsjZP7e.jpg)

**Comment by forivall** [comment]
This also occurs on iOS

**Comment by jeroensmeets** [comment]
images are not shown in v1.0.10 as there is no acceptable solution for the animated GIFs in Fuse.

**Comment by jeroensmeets** [comment]
when FuseTools can show animated gifs i'll add them back in.

**Comment by jeroensmeets** [comment]
Closing for now, the static images are displayed. As I said: I will add the animated avatars back in once FuseTools supports it.
