### ISSUE TITLE
Release 11t on F-droid

### ISSUE THREAD

**Issue by ghost** [jeroensmeets/mastodon-app#68]
Is it possible to launch this on their build system?

**Comment by jeroensmeets** [comment]
As this question keeps popping up ;-) I'll leave this issue as enhancement. Have my hands full at the moment with the two versions I support (Android Play Store and iOS App Store).

On the other hand: all code is here on github. Feel free to run with it!

**Comment by IzzySoft** [comment]
Maybe, meanwhile just publish the `.apk` here at Github, so the "Google-free" folks have a chance to grab it? Preferably placed on the `releases/` page (see: [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help), so my updater script could automatically grab it and put it into [my F-Droid compatible repo](https://android.izzysoft.de/repo) :innocent:

**Comment by jeroensmeets** [comment]
Understand your point, I will keep focussing on the Play and App Store though and getting the app forward. If you'd like to have a go at it, all code is in this repo and should build correctly in fusetools. Let me know if you run into problems. And have fun! :-)

**Comment by Jojonintendo** [comment]
It would be absolutely wonderful to be able to install this app from F-Droid. Even an apk at github would be an awesome start :)

**Comment by IzzySoft** [comment]
@jeroensmeets thanks for understanding – but one point you missed was me asking for an *already built* `.apk` (e.g. the one you publish to Playstore anyway), signed with *your* key (so it can easily be cross-updated) – which I then could place into my above mentioned repo. First, I have no build environment setup myself, and second I don't want to introduce "yet another signature" into the chain, which would make it only more difficult. If signed with your key, people can at least cross-check the `.apk` with the one from Play. If F-Droid signs it for the "official repo", folks know to trust the F-Droid signature. Why should anyone trust mine (or any other 3rd party's) and assume it's genuine?

**Comment by jeroensmeets** [comment]
@IzzySoft you write: `cross-updated' -- how would this work? Do you need a new `.apk` for each version I release in the Play store?

**Comment by jeroensmeets** [comment]
@IzzySoft I'll take a look for the next public Play store version.

**Comment by IzzySoft** [comment]
No need for "old versions" of course. And yes, whenever you release a new version, just attach the `.apk` to the corresponding "tag" on the `releases/` page, as described in the Github help on [Creating Releases](https://help.github.com/articles/creating-releases/) (see above ;) Once set up, it takes less than a minute to attach the file; my updater script would then catch it automatically within the following ~24h – so folks using my repo with their F-Droid client would automatically get notified and can update by a simple "tap".

<details>
As you removed that comment, you probably already found the answer yourself: with "cross-update" I meant that, if the app was already installed from one source, it could always be updated from the other source as well – wherever the update appears first. Also makes it easier for those just in the process of "switching sources", e.g. to get rid of proprietary dependencies like GApps on their devices :innocent:
</details>

**Comment by jeroensmeets** [comment]
@IzzySoft uploaded apk at https://github.com/jeroensmeets/mastodon-app/releases/tag/v1.1.17 . Will you let me know if your script can pick it up like this?

**Comment by IzzySoft** [comment]
@jeroensmeets Wonderful – will be picked up easy-peasy that way! And [it is already there now](https://apt.izzysoft.de/fdroid/index/apk/com.jeroensmeets.mastodon), and [also listed here](https://android.izzysoft.de/applists/category/named/network_twitter#group_1113) :innocent: :+1:

One suggestion (guess you already know, but just in case): the current package shows on `aapt` as

    package: name='com.jeroensmeets.mastodon' versionCode='17' versionName='1.1' platformBuildVersionName='6.0-2704002'

while the tag reads 1.1.17. Please make sure if you upload a new version that versionCode *and* versionName must be incremented, or the repo won't build and I'd have to manually kick out the offender :scream_cat:

So now: Feel free to link to my repo (next to the Playstore link), so non-Googlers now where to pick it up :stuck_out_tongue_winking_eye:

**Comment by meneer** [comment]
Installed the apk on my Jolla (smooth as always on sailfishos :) ), but the installed app fails to show the input fields on the login page.

**Comment by jeroensmeets** [comment]
@IzzySoft great! Apk will not upload to the Play Store with the same VersionCode and VersionName is updated for each (non-beta) release in the store anyway, so we're good here. Will add the link.

**Comment by jeroensmeets** [comment]
@meneer do you mean the input field for the Mastodon instance or the loginname/password fields? The 2nd pair is in a webview, so maybe the page not loading from the instance.

**Comment by IzzySoft** [comment]
@jeroensmeets Great! You can verify success for yourself by checking above link ~24h after having pushed the `.apk`.

**Comment by ghost** [comment]
@IzzySoft @jeroensmeets You guys are simply amazing :D

**Comment by Jojonintendo** [comment]
What transifex3 just said, you are doing an excellent work. I'm already using 11t, and enjoying it!

**Comment by jeroensmeets** [comment]
@IzzySoft added version 1.2 -- let me know if there are issues.

**Comment by IzzySoft** [comment]
Thanks, @jeroensmeets – auto-update worked fine, the repo [picked up the new release](https://apt.izzysoft.de/fdroid/index/apk/com.jeroensmeets.mastodon) :+1:
