### ISSUE TITLE
Wish: app notifications when mentioned, reposted, followed, favourited

### ISSUE THREAD

**Issue by jeroensmeets** [jeroensmeets/mastodon-app#7]

**Comment by coolstar** [comment]
This will require access to a streaming API. I've filed an issue regarding the existing WebSocket's authentication: https://github.com/Gargron/mastodon/issues/331

**Comment by puphime** [comment]
would suggest having the app run in the background, check for new interactions for the user periodically & display notifications. would be very useful. mind you i'm not experienced in android dev and don't know if i'm making any sense

**Comment by jeroensmeets** [comment]
Hi I'm closing all old issues from 2017 as I'm starting this app up again in a new development environment.
