### ISSUE TITLE
Add clarifying text to "Connect to Mastodon" start screen

### ISSUE THREAD

**Issue by bthallplz** [jeroensmeets/mastodon-app#97]
The "Connect to Mastodon" screen that one sees prior to authenticating the app with their Mastodon server isn't too clear about what the user should do with it and/or what they should type into its textarea.

Maybe change

> "To use Mastodon, you connect to an instance. This is the Mastodon server where you created your account."

To:

> "To use Mastodon, connect to an instance. Type below the URL of the Mastodon server where you created your account."

Additionally, maybe include the filler text of "e.g. mastodon.social" in the textarea.

This also assumes that the user already has an account, so for users without accounts, you may want to add a way of showing where they can currently register for accounts and load that in the webview.

**Comment by jeroensmeets** [comment]
Hi I'm closing all old issues from 2017 as I'm starting this app up again in a new development environment.
